# Generated by Django 5.2.3 on 2025-06-28 13:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_string', models.CharField(help_text='Known string encrypted using users master key', max_length=1024)),
                ('salt1', models.BinaryField(blank=True, help_text='Known string padding salt', null=True)),
                ('salt2', models.BinaryField(blank=True, help_text='Master key padding salt', null=True)),
                ('nonce', models.BinaryField(blank=True, help_text='Crypto nonce', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VaultEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Label or name of the service', max_length=100)),
                ('username', models.CharField(help_text='username or email used for the service', max_length=150)),
                ('encrypted_password', models.TextField(help_text='AES-encrypted password string')),
                ('salt', models.TextField(blank=True, help_text='Hash padding salt')),
                ('nonce', models.TextField(blank=True, help_text='Crypto nonce')),
                ('notes', models.TextField(blank=True, help_text='Optional notes or hints')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
