# Generated by Django 5.2.3 on 2025-06-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaultapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultentry',
            name='encrypted_password',
            field=models.CharField(help_text='AES-encrypted password string', max_length=1024),
        ),
        migrations.AlterField(
            model_name='vaultentry',
            name='nonce',
            field=models.BinaryField(blank=True, help_text='Crypto nonce', null=True),
        ),
        migrations.AlterField(
            model_name='vaultentry',
            name='salt',
            field=models.BinaryField(blank=True, help_text='Hash padding salt', null=True),
        ),
    ]
