# Generated by Django 5.2.3 on 2025-06-23 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaultapi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultentry',
            name='nonce',
            field=models.TextField(blank=True, help_text='Crypto nonce'),
        ),
        migrations.AlterField(
            model_name='vaultentry',
            name='salt',
            field=models.TextField(blank=True, help_text='Hash padding salt'),
        ),
        migrations.CreateModel(
            name='UserKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_string', models.CharField(help_text='Known string encrypted using users master key')),
                ('salt1', models.TextField(blank=True, help_text='Known string padding salt')),
                ('salt2', models.TextField(blank=True, help_text='Master key padding salt')),
                ('nonce', models.TextField(blank=True, help_text='Crypto nonce')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
