# Generated by Django 5.2.3 on 2025-07-03 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaultapi', '0003_emailchange'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailChange',
        ),
    ]
