# Generated by Django 5.2.3 on 2025-07-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaultapi', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
    ]
