# Generated by Django 5.2.3 on 2025-07-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaultapi', '0006_alter_userprofile_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultentry',
            name='tag',
            field=models.CharField(blank=True, help_text='optional tag added to entry', max_length=24),
        ),
    ]
