# Generated by Django 5.2.3 on 2025-07-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaultapi', '0007_vaultentry_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultentry',
            name='tag',
            field=models.TextField(blank=True, help_text='optional tag added to entry'),
        ),
    ]
