name: Cleanup Users

on:
    schedule:
        - cron: '0 0 * * *'
        - cron: '0 3 * * *'
        - cron: '0 6 * * *'
        - cron: '0 9 * * *'
        - cron: '0 12 * * *'
        - cron: '0 15 * * *'
        - cron: '0 18 * * *'
        - cron: '0 21 * * *'

jobs:
    cleanup:
        runs-on: ubuntu-latest
        steps:
            - name: Trigger cleanup endpoint
              run: |
                curl -X POST ${{ secrets.CLEANUP_ENDPOINT }} \
                -H "X_ADMIN_TOKEN: ${{ secrets.ADMIN_CLEANUP_TOKEN }}"
        
        env:
            ADMIN_CLEANUP_TOKEN: ${{ secrets.ADMIN_CLEANUP_TOKEN }}
